### ISSUE TITLE
Add Instruction in the beginning 

### ISSUE THREAD

**Issue by baidi-mannan** [baidi-mannan/Divide-Game#2]
Add a box which contains the set of instructions for the game

**Comment by Cyrus1219** [comment]
I would like to contribute in this !

**Comment by ghost** [comment]
Hello, I would like to work on this issue. Can you assign it to me?

**Comment by akshatjain-akj** [comment]
hello i would like to contribute in this issue can you assign it?

**Comment by baidi-mannan** [comment]
Assigning this to @AggiSahithi  on first come first serve basis.
   @akshatjain-akj , U are free to open more issues and contribute.

All the best!!

**Comment by baidi-mannan** [comment]
@AggiSahithi  Kindly post the List of Instructions/Rules here, before adding it to the code.

**Comment by ghost** [comment]
These are the rules I want to  add:
1. It is a 3*3 number grid.
2. Drag the numbers from the rightmost of 3 numbers suggested below into the grid, which initially is kept empty.
3. If an adjacent number is a factor of or is divisible by that number, the smaller number vanishes and the larger number is updated by the quotient and consequently, the score gets updated.
4. There is a blank box in the right bottom to which you can drag and save a number for later.
5. Game is over when the grid is filled with the numbers not divisible by each other.

**Comment by baidi-mannan** [comment]
LGTM✌️
You can add this in the beginning of the game..
When the user hits the play game button the instructions should appear in a box.
