### ISSUE TITLE
Spelling mistakes in README.md file

### ISSUE THREAD

**Issue by KamalAres** [baidi-mannan/Divide-Game#4]
I want to work on this issue. I request you to grant me permission to work on this issue.

**Comment by baidi-mannan** [comment]
Hi @KamalAres!! I guess you are a beginner in this open source world.
I like your enthusiasm towards the open source.
But still, Changing spellings won't make much difference.
Imo, if you really want to contribute to this project, then you should learn the basic JS and Algo which will hardly take 2-3 weeks.
U can still work on it if you wish.
I would love to see more contributions from your side.


Peace!!
