### ISSUE TITLE
Bug In the JS

### ISSUE THREAD

**Issue by baidi-mannan** [baidi-mannan/Divide-Game#6]
In this code we cannot divide the quotient of the dragged number divided by  a adjacent number with some other other adjacent  number.
Okay, It's complicated. Let's understand this with an example..

Suppose 7 and 2 are in the grid as shown in the pic
![DIVIDE - Google Chrome 06-12-2020 22_04_59 (2)](https://user-images.githubusercontent.com/68608356/101286320-d9857880-380f-11eb-81d6-0d9ca39b07bb.png)

And now if we place 14 in between them, then all 2,7 and 14 should disappear as per the rules.
But 14 is replaced by either 7 or 2.
![DIVIDE - Google Chrome 06-12-2020 22_05_07](https://user-images.githubusercontent.com/68608356/101286369-249f8b80-3810-11eb-9491-3a9784643c29.png)

Can someone come up with an idea, how to resolve this?

**Comment by ghost** [comment]
Hello, I would like to work on this. Can you please assign it to me?

**Comment by baidi-mannan** [comment]
Hello @AggiSahithi, can you please explain in brief what you will do to solve this issue??

**Comment by RisHaV-IITKGP** [comment]
Hello @baidi-mannan . I think I have a way to fix this bug. Please correct me if I am wrong.
We maintain a variable which stores the final value of the current cell (after reduction from the adjacent cell). Now we keep reducing the value of this variable if possible. In the end we assign this value to the current cell.
For example in the above case : initially fval = 14 , after reduction from 2 it becomes 14/2 = 7 , after reduction from 7 it becomes 7/7 = 1. We keep updating the value of fval after each function call.

**Comment by baidi-mannan** [comment]
Thank You for contributing!!
