### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by astroidworld** [baidi-mannan/Divide-Game#7]
Favicon is missing and needs to be added.

**Comment by astroidworld** [comment]
Can you please assign this work to me??

**Comment by munal0803** [comment]
I would like to contribute to this issue

**Comment by baidi-mannan** [comment]
Assigning it to @astroidworld  on first come first serve basis, 

@astroidworld  It would be better if you make 3-4 favicons so that I have enough options to choose.
